language: php

php:
    - 7.2
    - 7.3
    - 7.4

matrix:
    include:
        - php: 7.2
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable' SYMFONY_DEPRECATIONS_HELPER=weak
        - php: 7.4
          env: DEPENDENCIES=dev SYMFONY_DEPRECATIONS_HELPER=weak
        # Test against LTS versions
        - php: 7.2
          env: SYMFONY_VERSION=^3

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/lts:${SYMFONY_VERSION}" --no-update; fi;
    - if [ "$DEPENDENCIES" = "dev" ]; then composer config minimum-stability dev; fi;

install: composer update -n $COMPOSER_FLAGS

script: vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
