language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - nightly

matrix:
    include:
        - php: 5.4
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable' SYMFONY_DEPRECATIONS_HELPER=weak
        - php: 7.2
          env: DEPENDENCIES=dev SYMFONY_DEPRECATIONS_HELPER=weak
        - php: 5.3
          dist: precise
        # Test against LTS versions
        - php: 7.0
          env: SYMFONY_VERSION=^2
        - php: 7.1
          env: SYMFONY_VERSION=^3
    allow_failures:
        - php: nightly

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

before_install:
    - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/lts:${SYMFONY_VERSION}" --no-update; fi;
    - if [ "$DEPENDENCIES" = "dev" ]; then composer config minimum-stability dev; fi;

install: composer update -n $COMPOSER_FLAGS

script: vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
