language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - hhvm
    - nightly

matrix:
    include:
        - php: 5.3
          env: COMPOSER_FLAGS='--prefer-lowest --prefer-stable'
    allow_failures:
        - php: hhvm
        - php: nightly

sudo: false

cache:
    directories:
        - $HOME/.composer/cache/files

install: composer update -n $COMPOSER_FLAGS

script: vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
